import Head from 'next/head'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import WorkList from '@/components/WorkList'
import { useAppDispatch, useAppSelector } from '@/components/redux/hooks'
import { increment, incrementByAmount, selectCount } from '@/components/redux/reducers/counterSlice'
import { useEffect } from 'react'


export default function Home() {
  const count = useAppSelector((state) => state)
   const dispatch = useAppDispatch()
  //  
  

  useEffect(() => {
    dispatch(increment())

    
  }, [])
  useEffect(() => {
    console.log("renderHome",count)
 

    
  },)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
      <WorkList />

      
    </>
  )
}
